# Generated by Django 4.0.4 on 2022-06-21 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='Songs/')),
                ('image_file', models.ImageField(blank=True, default='Song_Image/default.jpg', null=True, upload_to='Song_Image/')),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('ROCK', 'Rock'), ('METAL', 'Metal'), ('POP', 'Pop'), ('HIP-HOP', 'Hip-Hop'), ('INDY', 'Indy'), ('COUNTRY', 'Country'), ('BLUES', 'Blues'), ('CLASSIC', 'Classic')], max_length=49)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 0, 10, 57, 999323))),
                ('data_created', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 0, 10, 58, 299))),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.song')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fav', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 0, 10, 58, 1297))),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
