# Generated by Django 4.0.4 on 2022-06-22 21:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 0, 0, 19, 494415)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 0, 0, 19, 493418)),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 0, 0, 19, 492420)),
        ),
    ]
